openapi: 3.0.3
info:
  title: OnlineVagtplan
  description: |-
    The OnlineVagtplan API
  version: "0.0"
  
tags:
- name: Shifts
- name: Shows
- name: User
paths:
  /shows:
    get:
      tags:
        - Shows
      summary: Get a list of all future shows
      responses:
        "200":
          description: Success
  /shifts:
    get:
      tags:
        - Shifts
      summary: Get an array of shifts
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Shift'
  /shifts/byUser:
    get:
      tags:
        - Shifts
      summary: Get an array of shifts for the logged in user
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Shift'
        "403":
          description: Not logged in
  /shifts/byUser/{username}:
    get:
      tags:
        - Shifts
      summary: Get an array of shifts for a given user
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
        "404":
          description: User not found
  /shifts/byShow/{showID}:
    get:
      tags:
        - Shifts
      summary: Get an array of shifts for a given show
      parameters:
        - name: showID
          in: path
          required: True
          schema:
            type: integer
      responses:
        "200":
          description: Success
        "400":
          description: Invalid show id
        "404":
          description: Show not found
    post:
      tags:
        - Shifts
      summary: Sign up for a shift
      parameters:
      - name: showID
        in: path
        required: true
        schema: 
          type: integer
      responses:
        "200":
          description: Success
        "403":
          description: Not logged in
    delete:
      tags:
        - Shifts
      summary: Delete a shift for the logged in user on the given show
      parameters:
      - name: showID
        in: path
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: Success
        "403":
          description: Not logged in
  /login:
    get:
      tags:
        - User
      summary: Login a user
      responses:
        "200":
          description: Success
  /logout:
    get:
      tags:
      - User
      summary: Logout a user
      responses:
        "200":
          description: Success
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: someID
  schemas:
    Shift:
      type: object
      properties:
        username:
          type: string
          example: gaben
        showID:
          type: integer
          example: 3
security:
  - cookieAuth: []
