openapi: 3.0.3
info:
  title: OnlineVagtplan
  description: |-
    The OnlineVagtplan API
  version: "0.0"
  
tags:
- name: Shifts
- name: Shows
paths:
  /shows:
    get:
      tags:
        - Shows
      summary: Get a list of all future shows
      responses:
        "200":
          description: Success
  /shifts:
    get:
      tags:
        - Shifts
      summary: Get a list of shifts
      responses:
        "200":
          description: Success
    post:
      tags:
        - Shifts
      summary: Sign up for a shift
      requestBody:
        description: Sign up for a shift
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Shift"
      responses:
        "200":
          description: Success
  /shifts/byUser/{username}:
    get:
      tags:
        - Shifts
      summary: Get a list of shifts for a given user
      parameters:
        - name: username
          in: path
          required: True
          schema:
            type: string
      responses:
        "200":
          description: Success
          
  /shifts/byShow/{showID}:
    get:
      tags:
        - Shifts
      summary: Get a list of shifts for a given show
      parameters:
        - name: showID
          in: path
          required: True
          schema:
            type: integer
      responses:
        "200":
          description: Success
          
components:
  schemas:
    Shift:
      type: object
      properties:
        username:
          type: string
          example: gaben
        showID:
          type: integer
          example: 3
                  
